

CONFIG_TOML_TEMPLATE_PATH = "assets/template_config.toml"

# theme default values
PRIMARY_COLOR_DEFAULT = "#ff4b4b"
BACKGROUND_COLOR_DEFAULT = "#ffffff"
SECONDARY_BACKGROUND_COLOR_DEFAULT = "#f0f2f6"
TEXT_COLOR_DEFAULT = "#31333f"

LINK_COLOR_DEFAULT = "#0054a3"
CODE_BG_COLOR_DEFAULT = "#f0f2f6"
BORDER_COLOR_DEFAULT = "#31333f20"
DATAFRAME_BORDER_COLOR_DEFAULT = "#31333f10"
DATAFRAME_HEADER_BG_COLOR_DEFAULT = "#f8f9fb"

SIDEBAR_PRIMARY_COLOR_DEFAULT = "#ff4b4b"
SIDEBAR_BACKGROUND_COLOR_DEFAULT = "#f0f2f6"
SIDEBAR_SECONDARY_BACKGROUND_COLOR_DEFAULT = "#ffffff"
SIDEBAR_TEXT_COLOR_DEFAULT = "#31333f"

SIDEBAR_LINK_COLOR_DEFAULT = "#0054a3"
SIDEBAR_CODE_BG_COLOR_DEFAULT = "#f0f2f6"
SIDEBAR_BORDER_COLOR_DEFAULT = "#31333f20"
SIDEBAR_DATAFRAME_BORDER_COLOR_DEFAULT = "#31333f10"
SIDEBAR_DATAFRAME_HEADER_BG_COLOR_DEFAULT = "#f8f9fb"