
PRIMARY_COLOR_DEFAULT = "#ff4b4b"
BACKGROUND_COLOR_DEFAULT = "#ffffff"
SECONDARY_BACKGROUND_COLOR_DEFAULT = "#f0f2f6"
TEXT_COLOR_DEFAULT = "#31333f"

LINK_COLOR_DEFAULT = "#0054a3"
CODE_BG_COLOR_DEFAULT = "#f0f2f6"
BORDER_COLOR_DEFAULT = "#31333f20"
DATAFRAME_BORDER_COLOR_DEFAULT = "#31333f10"
DATAFRAME_HEADER_BG_COLOR_DEFAULT = "#f8f9fb"